apiVersion: initialization.kcp.io/v1alpha1
kind: InitTemplate
metadata:
  name: openmcp-managed-control-plane
spec:
  template: |
    apiVersion: core.opencp.cloud/v1alpha1
    kind: ManagedControlPlane
    metadata:
      name: default
