apiVersion: gardener.orchestrate.cloud.sap/v1alpha1
kind: ProviderConfig
metadata:
  name: gardener-default-my-shoot2
spec:
  credentials:
    secretRef:
      key: kubeconfig
      name: gardener-project-my-shoot2-kubeconfig
      namespace: default
    source: Secret

---

apiVersion: gardener.orchestrate.cloud.sap/v1alpha1
kind: AdminKubeconfigRequest
metadata:
  name: gardener-default-my-shoot2
spec:
  forProvider:
    validFor: 1h
    renewAfter: 45m
    shootRef:
      name: my-cluster
      namespace: garden-om-587sf-d5638
  providerConfigRef:
    name: gardener-default-my-shoot2
  writeConnectionSecretToRef:
    name: my-cluster.kubeconfig
    namespace: default