apiVersion: crossplane.services.openmcp.cloud/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  versions:
    - version: $CROSSPLANE_DOCKER_IMAGE_TAG
      chart:
        url: $CROSSPLANE_CHART_IMAGE
      image:
        url: $CROSSPLANE_DOCKER_IMAGE
  providers:
    availableProviders:
      # - name: provider-kubernetes
      #   package: $CROSSPLANE_PROVIDER_KUBERNETES_IMAGE
      #   versions:
      #     - $CROSSPLANE_PROVIDER_KUBERNETES_IMAGE_TAG
      - name: provider-kubernetes
        package: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
        versions:
          - v1.2.1
