apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: openmcp.cloud
  labels:
    ui.platform-mesh.io/content-for: openmcp.cloud
spec:
  latestResourceSchemas:
    - v260218-a16964f.crossplanes.crossplane.services.openmcp.cloud
  permissionClaims:
    - group: apis.kcp.io
      resource: apiexports
      all: true
    - group: ui.platform-mesh.io
      resource: contentconfigurations
      all: true
      identityHash: f4c5f7f3e49e8afbe23a635cdbe916ba45fa557161d1f6b3c94029157b49766e
status: {}
