apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: openmcp.cloud
  labels:
    ui.platform-mesh.io/content-for: openmcp.cloud
spec:
  latestResourceSchemas:
    - v260218-a16964f.crossplanes.crossplane.services.openmcp.cloud
  permissionClaims:
    - group: apis.kcp.io
      resource: apiexports
      all: true
    - group: ui.platform-mesh.io
      resource: contentconfigurations
      all: true
      identityHash: fab42e602e43c50ca883b9661370221d922c67b305dfe71ec4126342a4c3e9b2
status: {}
