apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: openmcp.cloud
  labels:
    ui.platform-mesh.io/content-for: openmcp.cloud
spec:
  latestResourceSchemas:
    - v260218-a16964f.crossplanes.crossplane.services.openmcp.cloud
  permissionClaims:
    - group: apis.kcp.io
      resource: apiexports
      all: true
    - group: ui.platform-mesh.io
      resource: contentconfigurations
      all: true
      identityHash: 13c5a3e2dece720df31a0d8790a08e58ca258d7eb91982dc791ec755c017d1a4
status: {}
