{{- if .Values.initializer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-initializer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.initializer.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-initializer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-initializer
        control-plane: controller-manager
        service: {{ .Release.Name }}
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          args:
          - initializer
          - "--health-probe-bind-address=:{{ .Values.health.port }}"
          - "--log-level={{ .Values.log.level }}"
          {{- if .Values.log.noJson }}
          - "--no-json"
          {{- end }}
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - name: health-port
            containerPort: {{ .Values.health.port }}
            protocol: TCP
          env:
          - name: KCP_KUBECONFIG
            value: /var/opt/kcp/kubeconfig
          - name: REGION
            value: {{ .Values.region | default "local" }}
          - name: ENVIRONMENT
            value: {{ .Values.environment | default "local" }}
          - name: IMAGE_TAG
            value: "{{ .Values.image.tag }}"
          - name: MCP_ISSUERURL
            value: {{ (.Values.mcp).issuerURL }}
          - name: KCP_INITIALIZER_INITIALIZINGVIRTUALWORKSPACEURL
            value: {{ .Values.initializer.initializingVirtualWorkspaceURL }}
          - name: KCP_INITIALIZER_INITIALIZER
            value: {{ .Values.initializer.initializerName | default "openmcp-init" }}
          {{- if .Values.tracing.enabled }}
          {{- include "common.collectorEnvironment" . | nindent 10 }}
          {{- end }}
          {{- include "common.operatorHealthAndReadyness" . | nindent 10 }}
          {{- include "common.resources" . | nindent 10 }}
          volumeMounts:
          - name: kcp-kubeconfig
            mountPath: /var/opt/kcp
      terminationGracePeriodSeconds: 10
      volumes:
      - name: kcp-kubeconfig
        secret:
          secretName: kcp-kubeconfig
{{- end }}
