{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-kubeconfig
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
    name: {{ .Values.externalSecrets.secretStore.name | default "environment-store" }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: mcp-kubeconfig
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.mcpKubeconfig.key }}
        property: config
      secretKey: config
{{- end }}
