apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
- apiGroups:
  - "core.openmcp.cloud"
  resources:
  - managedcontrolplanev2s
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "crossplane.services.opencp.cloud"
  resources:
  - crossplanes
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "crossplane.services.opencp.cloud"
  resources:
  - crossplanes/status
  verbs:
  - "update"
  - "patch"
- apiGroups:
  - "crossplane.services.openmcp.cloud"
  resources:
  - crossplanes
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "core.opencp.cloud"
  resources:
  - managedcontrolplanes
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "core.opencp.cloud"
  resources:
  - managedcontrolplanes/status
  verbs:
  - "update"
  - "patch"
- apiGroups:
  - "syncagent.kcp.io"
  resources:
  - publishedresources
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "pkg.crossplane.io"
  resources:
  - providers
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "apis.kcp.io"
  resources:
  - apiresourceschemas
  - apiexports
  - apibindings
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "kro.services.opencp.cloud"
  resources:
  - kros
  - kros/status
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "flux.services.opencp.cloud"
  resources:
  - fluxes
  - fluxes/status
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "ocm.services.opencp.cloud"
  resources:
  - ocmcontrollers
  - ocmcontrollers/status
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
