apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: gardener.cloud
spec:
  permissionClaims:
    - resource: secrets
      verbs:
        - '*'
  resources:
    - group: gardener.cloud
      name: gardenerprojects
      schema: v260310-e532c57.gardenerprojects.gardener.cloud
      storage:
        crd: {}
status: {}
