apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  labels:
    ui.platform-mesh.io/content-for: gardener.cloud
  name: gardener.cloud
spec:
  permissionClaims:
    - resource: secrets
      verbs:
        - '*'
  resources:
    - group: gardener.cloud
      name: gardenerprojects
      schema: v260310-b7b9b3b.gardenerprojects.gardener.cloud
      storage:
        crd: {}
status: {}
