apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: openmcp.cloud
  labels:
    ui.platform-mesh.io/content-for: openmcp.cloud
spec:
  latestResourceSchemas:
    - v260218-a16964f.crossplanes.crossplane.services.openmcp.cloud
    - v260307-567f630.managedcontrolplanes.crossplane.services.openmcp.cloud
  permissionClaims:
    - group: apis.kcp.io
      resource: apiexports
      all: true
    - group: ui.platform-mesh.io
      resource: contentconfigurations
      all: true
status: {}
