apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v260311-2892093.fluxcatalogs.flux.services.opencp.cloud
spec:
  group: flux.services.opencp.cloud
  names:
    kind: FluxCatalog
    listKind: FluxCatalogList
    plural: fluxcatalogs
    singular: fluxcatalog
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      description: FluxCatalog is a read-only catalog of available Flux versions.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: spec defines the available Flux versions
          properties:
            versions:
              description: Available Flux versions.
              items:
                description: FluxCatalogVersion represents an available Flux version.
                properties:
                  chartVersion:
                    description: ChartVersion is the helm chart version/tag (e.g.
                      "2.14.0").
                    type: string
                  version:
                    description: Version is the upstream application version (e.g.
                      "v2.4.0").
                    type: string
                required:
                - version
                type: object
              type: array
          required:
          - versions
          type: object
      required:
      - spec
      type: object
    served: true
    storage: true
    subresources: {}
