apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: openmcp.cloud
  labels:
    ui.platform-mesh.io/content-for: openmcp.cloud
spec:
  resources:
    - group: crossplane.services.openmcp.cloud
      name: crossplanecatalogs
      schema: v260308-657c3cf.crossplanecatalogs.crossplane.services.openmcp.cloud
      storage:
        crd: {}
    - group: crossplane.services.openmcp.cloud
      name: crossplanes
      schema: v260218-a16964f.crossplanes.crossplane.services.openmcp.cloud
      storage:
        crd: {}
    - group: core.openmcp.cloud
      name: managedcontrolplanes
      schema: v260308-d0e7cae.managedcontrolplanes.core.openmcp.cloud
      storage:
        crd: {}
    - group: kro.services.openmcp.cloud
      name: krocatalogs
      schema: v260311-2892093.krocatalogs.kro.services.openmcp.cloud
      storage:
        crd: {}
    - group: kro.services.openmcp.cloud
      name: kros
      schema: v260311-2892093.kros.kro.services.openmcp.cloud
      storage:
        crd: {}
    - group: flux.services.openmcp.cloud
      name: fluxcatalogs
      schema: v260311-2892093.fluxcatalogs.flux.services.openmcp.cloud
      storage:
        crd: {}
    - group: flux.services.openmcp.cloud
      name: fluxes
      schema: v260311-2892093.fluxes.flux.services.openmcp.cloud
      storage:
        crd: {}
    - group: ocm.services.openmcp.cloud
      name: ocmcontrollercatalogs
      schema: v260311-2892093.ocmcontrollercatalogs.ocm.services.openmcp.cloud
      storage:
        crd: {}
    - group: ocm.services.openmcp.cloud
      name: ocmcontrollers
      schema: v260311-2892093.ocmcontrollers.ocm.services.openmcp.cloud
      storage:
        crd: {}
  permissionClaims:
    - group: apis.kcp.io
      resource: apiexports
      verbs:
        - '*'
    - group: apis.kcp.io
      resource: apiresourceschemas
      verbs:
        - '*'
    - group: ui.platform-mesh.io
      resource: contentconfigurations
      verbs:
        - '*'
      identityHash: 137d64373608592f365074526a2e2208468978775375b0423d70a7504b7b8eaf
    - group: rbac.authorization.k8s.io
      resource: clusterroles
      verbs:
        - '*'
    - group: rbac.authorization.k8s.io
      resource: clusterrolebindings
      verbs:
        - '*'
    - group: apiextensions.k8s.io
      resource: customresourcedefinitions
      verbs:
        - '*'
status: {}
