apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: openmcp-internal.cloud
spec:
  resources:
    - group: crossplane.services.openmcp.cloud
      name: crossplanecatalogs
      schema: v260308-657c3cf.crossplanecatalogs.crossplane.services.openmcp.cloud
      storage:
        crd: {}
status: {}
