events{}

http {
    include /etc/nginx/mime.types;

    server {
        listen 8080;

        root /usr/share/nginx/html;

        location /ui/openmcp/wc/ {
            try_files $uri $uri/ /ui/openmcp/wc/index.html;
        }

        location /ui/openmcp/wc {
            rewrite ^/ui/openmcp/wc$ /ui/openmcp/wc/ permanent;
        }

        location /healthz {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_min_length 1000;
    }
}
