events{}

http {
    include /etc/nginx/mime.types;

    server {
        listen 8080;

        root /usr/share/nginx/html;

        location /ui/openmcp/wc/ {
            try_files $uri $uri/ /wc/index.html;
        }

        location /healthz {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
}
