# Flux Helm values placeholder
# Customize these values for the Flux installation
installCRDs: true
cli:
  image: ghcr.io/fluxcd/flux-cli
  tag: v2.4.0
helmController:
  create: true
imageAutomationController:
  create: false
imageReflectionController:
  create: false
kustomizeController:
  create: true
notificationController:
  create: true
sourceController:
  create: true
