apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-event-showcase
  namespace: default
spec:
  interval: 1m
  url: https://github.com/openmcp-project/local-event-showcase
  ref:
    branch: feat/kgg-deploy