apiVersion: demo.local/v1alpha1
kind: GardenerShoot
metadata:
  name: my-test-shoot
  namespace: default
spec:
  parameters:
    projectName: local
    shootName: crossplane-test
    kubernetesVersion: "1.31.1"
    purpose: evaluation
    workerMinimum: 1
    workerMaximum: 2
